/* 여러 페이지에 중복해서 쓰이는 components */
export {
  Button,
  CourseUtillityModal,
  DeleteModal,
  Footer,
  Header,
  HistoriesForm,
  Icon,
  Input,
  MenuListForm,
  NextBtn,
  OrderingButton,
  OrderingModal,
  PageContainer,
  ProfilePic,
  ReportForm,
  Section,
  SmallProfilePic,
  ToTopBtn,
  UtilDiv,
  UtilForm,
  UtilInputWrap,
  UtilTitle,
} from './common/';

/* 특정 페이지에서만 쓰이는 요소들 */
export {
  CourseDetailForm,
  CourseRegistrationForm,
  CoursesForm,
  DaumAddressApiForm,
  DisplayFindedIdForm,
  FollowsForm,
  InputAddressForm,
  InputDetailAddressForm,
  InputEmailForm,
  InputPasswordForm,
  InputUserForm,
  LoadingForm,
  LoginForm,
  MainSection,
  RankersForm,
  UserPageForm,
  WithdrawUserForm,
} from './ui/';

/* pages */
export {
  CourseDetail,
  CourseRegistration,
  Courses,
  EditUserMenu,
  FindingUserPage,
  Follows,
  Histories,
  InputAddress,
  InputDetailAddress,
  InputEmail,
  InputPassword,
  InputUser,
  Loading,
  Login,
  Main,
  Messages,
  Rankers,
  User,
  WithdrawUser,
} from './pages/';
