export {
  // Auth
  fetchUser,
  fetchCourseAuthor,
  updateUserAddress,
  updateUserPassword,
  checkIsDuplicatedId,
  checkIsDuplicatedNickname,
  signUpOrEditUser,
  withdrawUser,
  sendCertificationNumber,
  compareCertificationNumber,
  // Cosmost
  fetchCourseDetail,
  deleteCourse,
  fetchCategories,
  // Comment
  fetchSingleCourseView,
  postCourseReview,
  updateCourseReview,
  deleteCourseReview,
  // Popularity
  fetchCourseAverageRate,
  fetchCourseLikeCount,
  handleLikeCourseReview,
  likedCourseReview,
  handleLikeCourse,
  checkLikedCourse,
  fetchCourseReviewLikeCount,
  handleFollow,
  fetchIsFollowed,
  fetchMyFollowersCount,
  fetchMyFollowingsCount,
  fetchAuthorsFollowersCount,
  // Board
  fetchReportCategories,
  postReport,
  updateReport,
  deleteMyReport,
  fetchAnswerAboutMyReport,
} from './api';
